### ISSUE TITLE
npm module publish test

### ISSUE THREAD

**Issue by oleg-baturov** [norestlabs/dknowledgr#4]
Try to publish and test if it works as module.

**Comment by z-th-btc** [comment]
![image](https://user-images.githubusercontent.com/42106554/49674391-8c099000-fabd-11e8-8e73-694006199250.png)

![image](https://user-images.githubusercontent.com/42106554/49675384-27e8cb00-fac1-11e8-91be-f72bd329a365.png)

![image](https://user-images.githubusercontent.com/42106554/49675376-1c959f80-fac1-11e8-9554-ff0badf4fd1c.png)

**Comment by z-th-btc** [comment]
npm package setting is correct.
it works.

**Comment by oleg-baturov** [comment]
good so far.
